In [13]:
from random import randint

In [71]:
def race(positions=None):
    positions=positions or [3,6,8,11,14,17,14,11,8,6,3]
    if min(positions):
        return race([[j,j-1][i==z] for z in[random.randint(1,6)+random.randint(1,6)]for i,j in enumerate(positions,2)])
    else:
        return positions.index(0)+2, 101-sum(positions)

In [86]:
race()

(4, 71)

In [90]:
results={}
for i in range(10000):  results[z] = results.get((z:=race()[1]), 0) + 1

In [91]:
for i in sorted(results):
    print(i,results[i])

5 2
6 3
7 4
8 8
9 10
10 15
11 20
12 21
13 26
14 24
15 20
16 32
17 33
18 46
19 44
20 53
21 53
22 61
23 56
24 73
25 79
26 84
27 85
28 94
29 96
30 112
31 113
32 129
33 141
34 135
35 160
36 164
37 152
38 182
39 163
40 200
41 197
42 176
43 210
44 236
45 238
46 248
47 264
48 256
49 266
50 280
51 260
52 261
53 272
54 284
55 247
56 267
57 248
58 283
59 263
60 229
61 247
62 241
63 228
64 222
65 200
66 193
67 139
68 173
69 131
70 115
71 88
72 71
73 73
74 46
75 47
76 41
77 25
78 16
79 10
80 9
81 2
82 1
83 3
84 1


In [ ]:
# Chance of horse 2 winning on move 40
# P(Roll 2 on Move 40)
# P(Roll 2 2x in 39 moves)


In [3]:
known = dict()
def get_win_probs(pos=None):
    if pos is None:
        pos = start_pos
    if 0 in pos:
        return [float(i == 0) for i in pos]
    else:
        dkey = ''.join([chr(i+64) for i in pos])
        if dkey not in known:
            known[dkey] = [sum(i) 
                           for i in zip(*[[j*move_probs[i] 
                                            for j in get_win_probs([k-1 if j == i else k 
                                                                    for j, k in enumerate(pos)])]
                                           for i in range(len(move_probs))])]            

        return known[dkey]

get_win_probs()

[0.30235316878142704, 0.3952936624371459, 0.30235316878142704]

In [48]:
known

{'AAA': [0.2777777777777778, 0.4444444444444444, 0.2777777777777778],
 'AAB': [0.3549382716049383, 0.5679012345679012, 0.0771604938271605],
 'AAC': [0.37637174211248287, 0.6021947873799726, 0.021433470507544586],
 'ABA': [0.4012345679012346, 0.19753086419753085, 0.4012345679012346],
 'ABB': [0.5469821673525377, 0.3072702331961591, 0.14574759945130317],
 'ABC': [0.5969935985368084, 0.3529949702789209, 0.0500114311842707],
 'ACA': [0.4561042524005487, 0.0877914951989026, 0.4561042524005487],
 'ACB': [0.6475765889346137, 0.16095107453132143, 0.19147233653406492],
 'ACC': [0.7229906518315298, 0.20159528527155413, 0.07541406289691613],
 'ADA': [0.48049077884468827, 0.039018442310623375, 0.48049077884468827],
 'ADB': [0.6990592558722417, 0.08237226710020491, 0.21856847702755336],
 'ADC': [0.793290083000747, 0.11247908987074764, 0.09423082712850532],
 'BAA': [0.0771604938271605, 0.5679012345679012, 0.3549382716049383],
 'BAB': [0.12002743484224968, 0.7599451303155007, 0.12002743484224968],
 '

In [15]:
# Simulation
ntrials = 1000000

rnd_thresh = np.expand_dims(np.cumsum(move_probs), 0)
scenarios = np.stack([start_pos]*ntrials)
game_on = np.arange(ntrials)

while game_on.shape[0]:
    mvix = np.min(np.where(np.random.random((game_on.shape[0], 1)) < rnd_thresh, 
                           np.expand_dims(np.arange(rnd_thresh.shape[1]), 0), 
                           rnd_thresh.shape[1]), axis=1)
    scenarios[game_on, mvix] -= 1
    game_on = game_on[scenarios[game_on, mvix] != 0]

v, c = np.unique(np.sum(np.where(scenarios == 0, 
                                 np.expand_dims(np.arange(len(start_pos)), 0), 
                                 0), 
                        axis=1),
                 return_counts=True)
c = c / np.sum(c)

np.column_stack((v.astype(object), c.astype(object)))

array([[0, 0.301622],
       [1, 0.395109],
       [2, 0.303269]], dtype=object)

In [22]:
# Probability of horse 1 winning on 6th turn
t = 1
h = 0
move_probs[h], start_pos[h], t

(0.2777777777777778, 3, 1)

In [53]:
(move_probs[h] ** np.arange(100)) * ((1-move_probs[h]) ** (t-start_pos[h]))

array([1.00000000e+00, 2.77777778e-01, 7.71604938e-02, 2.14334705e-02,
       5.95374181e-03, 1.65381717e-03, 4.59393658e-04, 1.27609349e-04,
       3.54470415e-05, 9.84640042e-06, 2.73511123e-06, 7.59753119e-07,
       2.11042533e-07, 5.86229258e-08, 1.62841461e-08, 4.52337391e-09,
       1.25649275e-09, 3.49025764e-10, 9.69516012e-11, 2.69310003e-11,
       7.48083343e-12, 2.07800929e-12, 5.77224802e-13, 1.60340223e-13,
       4.45389507e-14, 1.23719308e-14, 3.43664743e-15, 9.54624287e-16,
       2.65173413e-16, 7.36592814e-17, 2.04609115e-17, 5.68358653e-18,
       1.57877404e-18, 4.38548343e-19, 1.21818984e-19, 3.38386067e-20,
       9.39961298e-21, 2.61100361e-21, 7.25278779e-22, 2.01466328e-22,
       5.59628688e-23, 1.55452413e-23, 4.31812259e-24, 1.19947850e-24,
       3.33188472e-25, 9.25523532e-26, 2.57089870e-26, 7.14138528e-27,
       1.98371813e-27, 5.51032815e-28, 1.53064671e-28, 4.25179641e-29,
       1.18105456e-29, 3.28070711e-30, 9.11307530e-31, 2.53140980e-31,
      

In [47]:
tv1 = [[((move_probs[h] ** start_pos[h]) 
         * ((1-move_probs[h]) ** (t-start_pos[h]))
         * n_choose_m(t-1, start_pos[h]-1))
        for h in range(1)] #len(start_pos))]
       for t in range(1, 10)]
np.cumsum(tv1)

array([0.        , 0.        , 0.02143347, 0.06787266, 0.13495148,
       0.21569451, 0.30316613, 0.39160965, 0.47677748])

In [50]:
tv2 = [(move_probs[0] ** i) * ((1-move_probs[0]) ** (5-i)) * n_choose_m(5, i) for i in range(6)]
tv2

[0.19649623617673456,
 0.3778773772629511,
 0.2906749055868855,
 0.11179804061034057,
 0.021499623194296266,
 0.0016538171687920206]

In [51]:
tv2[2] * move_probs[h]

0.08074302932969042

In [ ]:
def p_no_other_winner(nturns, horses):
    if len(horses) == 0:
        return float(nturns == 0.)
    else:
        pickprob = move_probs[horses[0]] / sum([move_probs[i] for i in horses])
        return sum([p_npicks(pickprob, nturns, i)
                    * p_no_other_winner(nturns-i, horses[1:])
                    for i in range(min(nturns, start_pos[horses[0]])+1)])

In [ ]:
nturns = 7
horses = []
p_no_other_winner(nturns, horses)

In [ ]:
pickprob = move_probs[horses[0]] / sum([move_probs[i] for i in horses])
pickprob

In [ ]:
for i in range(nturns+1):
    if i < start_pos[horses[0]]:
        print(i, p_npicks(pickprob, nturns, i))

In [ ]:
((ppick ** npicks) 
            * ((1-ppick) ** (nturns-npicks))
            * n_choose_m(nturns, npicks))

In [ ]:
p_npicks(move_probs[horses[0]] / sum([move_probs[i] for i in horses]), 
                             nturns, i)

In [ ]:
p_no_other_winner(nturns-i, horses[1:])

In [ ]:
[p_npicks(move_probs[horses[0]] / sum([move_probs[i] for i in horses]), 
                             nturns, i) 
                    * p_no_other_winner(nturns-i, horses[1:])
                    for i in range(min(nturns, start_pos[horses[0]])+1)]

In [ ]:
sum([p_npicks(horses[0], nturns, i) * p_no_other_winner(nturns-i, horses[1:])
 for i in range(min(nturns, start_pos[horses[0]]))])

In [ ]:
# Probability of horse 10 having been picked 0 times in prior 49 turns
p_npicks(10, 1, 0)

In [ ]:
move_probs[10]

In [ ]:
n = 49
m = 10

In [ ]:
n_choose_m(t-1, start_pos[3]-1)

In [18]:
def n_choose_m(n, m):
    r = 1
    for i in range(m):
        r *= (n-i)/(m-i)
    return round(r)

def p_npicks(ppick, nturns, npicks):
    return ((ppick ** npicks) 
            * ((1-ppick) ** (nturns-npicks))
            * n_choose_m(nturns, npicks))

In [ ]:
tv1 = np.random.random((1000000, 3))

In [ ]:
tv2 = np.where(tv1 < 0.5, 'A', np.where(tv1 < 0.8, 'B', 'C')).reshape(-1).view('<U3')
tv2